//#include "TokenType.h"

enum TokenType 
{
	NONE, PLUS, MINUS, MUL, DIV, LBRACKET, RBRACKET, LCURLBRACKET,
	RCURLBRACKET, LSQBRACKET, RSQBRACKET, EQ, EQEQ, INTWORD, FLOATWORD, VARWORD, CONSTWORD, INTLIT, DECLIT, EXCLA, IDENTIFIER, IF, WHILE,
	SEMICOLON, COMMA, ELSE, EXCLAEQ, SMALL, BIG, SMALLEQ, BIGEQ, AND, OR, MOD, 
};