//#include "TokenType.h"

enum TokenType
{
	NONE, PLUS, MINUS, MUL, DIV, LBRACKET, RBRACKET, LCURLBRACKET,
	RCURLBRACKET, LSQBRACKET, RSQBRACKET, EQ, EQEQ, INTWORD, FLOATWORD, CHARWORD,
	VOIDWORD, VARWORD, CONSTWORD, INTLIT, DECLIT, CHARLIT, EXCLA, IDENTIFIER, IF,
	WHILE, SEMICOLON, COMMA, ELSE, EXCLAEQ, SMALL, BIG, SMALLEQ, BIGEQ, AND, OR,
	MOD, FUNC, RETURN, MAKRO, QUOTMARK, STRINGWORD, STRINGLIT
};