#include "TokenType.h"

enum TokenType {
	NONE, PLUS, MINUS, MUL, DIV, LBRACKET, RBRACKET, LCURLBRACKET,
	RCURLBRACKET, EQ, EQEQ, INTWORD, FLOATWORD, VARWORD, CONSTWORD, INTLIT, DECLIT, EXCLA, IDENTIFIER, IF, WHILE,
	SEMICOLON, ELSE, EXCLAEQ, SMALL, BIG, SMALLEQ, BIGEQ, AND, OR, MOD
};